version: '3'

services:
  analysis-service:
    build: ./analysis-service
    volumes:
     - ./analysis-service:/usr/src/app
     - bluedropdata:/data
    depends_on:
     - db

  webserver:
    build: ./webserver
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./webserver:/var/www
     - bluedropdata:/srv
    depends_on:
     - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    depends_on:
     - db
     
  db:
    image: mariadb:10.1.22
    volumes:
     - ./webserver/mariadb:/etc/mysql/conf.d
     - /var/lib/mysql
    environment:
     - "MYSQL_DATABASE=bluedropdb"
     - "MYSQL_USER=bluedrop"
     - "MYSQL_PASSWORD=bluedrop"
     - "MYSQL_ROOT_PASSWORD=123456"
    ports:
     - "3306:3306"
     
volumes:
  bluedropdata:
    driver: local
    